[package]
name = "examples"
version = "0.0.0"
publish = false
edition = "2018"

[dev-dependencies]
tokio = { version = "0.3.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
srpc-macros = { version = "0.1", path = "../srpc-macros" }
srpc = { version = "0.1", path = "../srpc" }

[[example]]
name = "server"
path = "example_server.rs"